SELECT
  STUDENT_IS.DOCUMENT_GL.DATAFAKT,
  STUDENT_IS.DOCUMENT_GL.NOMERFAKT
FROM
  STUDENT_IS.DOCUMENT_GL
WHERE
  STUDENT_IS.DOCUMENT_GL.DATAFAKT IS NOT NULL OR
  STUDENT_IS.DOCUMENT_GL.NOMERFAKT IS NOT NULL
ORDER BY
  STUDENT_IS.DOCUMENT_GL.DATAFAKT