SELECT
  OPER_ID,
  NOMERFAKT AS "Номер на фактура",
  TO_CHAR(DATAFAKT, 'DD.MM.YYYY') AS "Дата на фактура",
  ROUND((SYSDATE-DATAFAKT),2) AS "Разлика"
FROM
  STUDENT_IS.DOCUMENT_GL
WHERE
  OPER_ID = '2' AND
  DATAFAKT >= TO_DATE('01.01.2013','DD.MM.YYYY') AND
  DATAFAKT <= TO_DATE('31.12.2013', 'DD.MM.YYYY')