SELECT OPERATOR_NAME, ZAPLATA, 
  (CASE
     WHEN ZAPLATA < 500 THEN ZAPLATA + (ZAPLATA * 0.35)
     WHEN ZAPLATA BETWEEN 500 AND 1000 THEN ZAPLATA + (ZAPLATA * 0.15)
     WHEN ZAPLATA BETWEEN 1000 AND 1500 THEN ZAPLATA + (ZAPLATA * 0.05)
  END) AS SALARY
FROM 
  STUDENT_IS.OPERATORS