SELECT
  STUDENT_IS.DOCUMENT_GL.NOMERFAKT,
  TO_CHAR(DOCUMENT_GL.DATAFAKT,'DD.MONTH.YYYY') AS "DATA"
FROM
  STUDENT_IS.DOCUMENT_GL
WHERE
  LOWER(TO_CHAR(DOCUMENT_GL.DATAFAKT,'DD.MONTH.YYYY')) LIKE '%january%'
ORDER BY
  TO_CHAR(DATAFAKT, 'DD')