SELECT
  ws.SKLAD_NAME,
  pg.PROD_GRUPA_NAME,
  p1.PRODKOD,
  p1.PRODNAME,
  p1.MERKA,
  s.KOLICHESTWO
FROM
  STUDENT_IS.PRODUCTS_GRUPA pg,
  STUDENT_IS.PRODUCTS p1,
  STUDENT_IS.SKLAD s,
  STUDENT_IS.WID_SKLAD ws
WHERE
  pg.PROD_GR_ID = p1.PROD_GR_ID AND
  p1.PRODKOD_ID =s.PRODKOD_ID AND
  s.SKLAD_ID = ws.SKLAD_ID AND
  s.KOLICHESTWO > 10 AND
  p1.MERKA = 'бр.'
ORDER BY
  ws.SKLAD_NAME,
  pg.PROD_GRUPA_NAME,
  p1.PRODKOD