SELECT
  pg.PROD_GRUPA_NAME,
  p1.PRODKOD,
  p1.PRODNAME,
  p1.MERKA,
  SUM(s.KOLICHESTWO) as KOLICHESTWO
FROM
  STUDENT_IS.PRODUCTS_GRUPA pg,
  STUDENT_IS.PRODUCTS p1,
  STUDENT_IS.SKLAD s
WHERE
  pg.PROD_GR_ID = p1.PROD_GR_ID AND
  p1.PRODKOD_ID = s.PRODKOD_ID AND
  p1.MERKA = 'бр.'
HAVING
  SUM(s.KOLICHESTWO) > 100
GROUP BY
  pg.PROD_GRUPA_NAME,
  p1.PRODKOD,
  p1.PRODNAME,
  p1.MERKA
ORDER BY
  pg.PROD_GRUPA_NAME,
  p1.PRODKOD