SELECT
  dg1.NOMERFAKT,
  dg1.DATAFAKT,
(
SELECT
  MAX(dg.OBSHTO) AS MAX_STOJNOST
FROM
  STUDENT_IS.DOCUMENT_GL dg
WHERE
  dg.TIP_DOC_ID = 1 AND
  dg.OPER_ID IN
(
SELECT
  o1.OPER_ID AS OPER_ID
FROM
  STUDENT_IS.OPERATORS o,
  STUDENT_IS.OPERATORS o1
WHERE
  o.OPER_ID = o1.OPER_ID_MASTER AND
  o.OPERATOR_NAME = 'Петър Петров') ) AS MAX_FAKT
FROM
  STUDENT_IS.DOCUMENT_GL dg1
WHERE
(
SELECT
  MAX(dg.OBSHTO) AS MAX_STOJNOST
FROM
  STUDENT_IS.DOCUMENT_GL dg
WHERE
  dg.TIP_DOC_ID = 1 AND
  dg.OPER_ID IN
(
SELECT
  o1.OPER_ID AS OPER_ID
FROM
  STUDENT_IS.OPERATORS o,
  STUDENT_IS.OPERATORS o1
WHERE
  o.OPER_ID = o1.OPER_ID_MASTER AND
  o.OPERATOR_NAME = 'Петър Петров')) = dg1.OBSHTO