SELECT
  p.PRODKOD,
  p.PRODNAME,
  p.MERKA,
  s.KOLICHESTWO
FROM
  STUDENT_IS.PRODUCTS p INNER JOIN
  STUDENT_IS.SKLAD s
  ON (p.PRODKOD_ID = s.PRODKOD_ID)
WHERE
  p.PRODKOD_ID = s.PRODKOD_ID AND
  LOWER(p.PRODNAME) = 'шоколадови пръчици 20/300' AND
  p.MERKA = 'бр.' AND
  s.KOLICHESTWO > 10