SELECT
  o.OPERATOR_NAME,
  o.DLAZNOST
FROM 
  STUDENT_IS.OPERATORS o
WHERE
  o.DLAZNOST = 
(
SELECT DISTINCT
  o1.DLAZNOST
FROM 
  STUDENT_IS.OPERATORS o1
WHERE
  LOWER(o1.OPERATOR_NAME) = 'рени енчева')