SELECT
  o.OPERATOR_NAME,
  o.DLAZNOST
FROM 
  STUDENT_IS.OPERATORS o
WHERE
  o.OPER_ID = 
(
 SELECT DISTINCT
  o1.OPER_ID_MASTER
 FROM
  STUDENT_IS.OPERATORS o1
 WHERE
  o1.OPERATOR_NAME = 'Иван Георгиев')