SELECT
  dg.NOMERFAKT,
  dg.DATAFAKT,
  c1.FIRMA
FROM
  STUDENT_IS.DOCUMENT_GL dg,
  STUDENT_IS.CLIENTS c1
WHERE
  dg.ID_CLIENT = c1.ID_CLIENT AND
  UPPER(c1.ADRES)
  IN
(
SELECT
  UPPER(c.ADRES)
FROM
  STUDENT_IS.CLIENTS c
WHERE
  c.FIRMA = 'Г-Сервиз - София')