SELECT DISTINCT
(
SELECT
  SUM(dg.OBSHTO)
FROM 
  STUDENT_IS.DOCUMENT_GL dg
WHERE
  dg.DATAFAKT >= TO_DATE('01.12.2013', 'dd.mm.yyyy') AND
  dg.DATAFAKT <= TO_DATE('31.12.2013', 'dd.mm.yyyy') AND
  dg.TIP_DOC_ID = 2) AS "DEC 13",
(
SELECT
  SUM(dg1.OBSHTO)
FROM
  STUDENT_IS.DOCUMENT_GL dg1
WHERE
  dg1.DATAFAKT >= TO_DATE('01.01.2014', 'dd.mm.yyyy') AND
  dg1.DATAFAKT <= TO_DATE('31.01.2014', 'dd.mm.yyyy') AND
  dg1.TIP_DOC_ID = 2) AS "JAN 14"
FROM
  STUDENT_IS.DOCUMENT_GL dg3